Repository Newt-Tea/eMarket-MSU-Intro-to-SE_Group1, pull requests merged in 2024-10, with the labels that each got.

#26 Diagram
  Diagrams/Data Files/Account Management Activity.csv
  Diagrams/Data Files/Account Management Class.csv
  Diagrams/Data Files/Account Management Sequence.csv
  Diagrams/Data Files/Account Management State.csv
  Diagrams/Data Files/Admin-Use-Case-Diagram.drawio
  Diagrams/Data Files/Class Overview Diagram.csv
  Diagrams/Data Files/Component-Diagram.drawio
  Diagrams/Data Files/Main-Product-Display-Class.drawio
  Diagrams/Data Files/Purchase and Payment State diagram.drawio.xml
  Diagrams/Data Files/Purchases and Payment Data.drawio.xml
  Diagrams/Data Files/Purchases and Payment Sequence Data.drawio.xml
  Diagrams/Data Files/Shopping cart Activity diagram.drawio
  Diagrams/Data Files/Shopping cart Sequence Diagram.drawio
  Diagrams/Data Files/Shopping cart State Diagram.drawio
  Diagrams/Data Files/Shopping cart Use case diagram.drawio
  Diagrams/Data Files/Sort-And-Search-Activity.drawio
  Diagrams/Data Files/Sort-And-Search-Class.drawio
  Diagrams/Data Files/Sort-And-Search-Sequence.drawio
  Diagrams/Data Files/Sort-And-Search-State.drawio
  Diagrams/Data Files/returns&RO.drawio.xml
  Diagrams/Images/Account Management Activity.png
  Diagrams/Images/Account Management Class.png
  Diagrams/Images/Account Management Sequence.png
  Diagrams/Images/Account Management State.png
  Diagrams/Images/Admin-Use-Case-Diagram.png
  Diagrams/Images/Architecural Design Diagram.png
  Diagrams/Images/Buyer Use Case Diagram.png
  Diagrams/Images/Class Overview Diagram.png
  Diagrams/Images/Component-Diagram.png
  Diagrams/Images/Main-Product-Display-Class.png
  Diagrams/Images/Purchase and Payment Sequence Diagram.drawio.png
  Diagrams/Images/Purchases and Payment Activity Diagram.drawio.png
  Diagrams/Images/Purchases and Payment State Diagram.drawio.png
  Diagrams/Images/Returns and Recent Order Class Diagram.drawio.png
  Diagrams/Images/Seller Use Case Diagram.png
  Diagrams/Images/Shopping cart Activity diagram.png
  Diagrams/Images/Shopping cart Sequence Diagram.png
  Diagrams/Images/Shopping cart State Diagram.png
  Diagrams/Images/Shopping cart Use case diagram.png
  Diagrams/Images/Sort-And-Search-Activity.png
  Diagrams/Images/Sort-And-Search-Class.png
  Diagrams/Images/Sort-And-Search-Sequence.png
  Diagrams/Images/Sort-And-Search-State.png
Labels: documentation

#38 Uploaded the blank Django webapp folder
  eMarket/db.sqlite3
  eMarket/eMarket/__init__.py
  eMarket/eMarket/__pycache__/__init__.cpython-312.pyc
  eMarket/eMarket/__pycache__/settings.cpython-312.pyc
  eMarket/eMarket/__pycache__/urls.cpython-312.pyc
  eMarket/eMarket/__pycache__/wsgi.cpython-312.pyc
  eMarket/eMarket/asgi.py
  eMarket/eMarket/settings.py
  eMarket/eMarket/urls.py
  eMarket/eMarket/wsgi.py
  eMarket/manage.py
Labels: Front-End, Back-End, DateBase

#37 Merge Documentation Issue Template
  .github/ISSUE_TEMPLATE/documentation.md
Labels: enhancement

#42 Pull Base functionality and login page
  eMarket/app/__init__.py
  eMarket/app/__pycache__/__init__.cpython-312.pyc
  eMarket/app/__pycache__/apps.cpython-312.pyc
  eMarket/app/__pycache__/models.cpython-312.pyc
  eMarket/app/admin.py
  eMarket/app/apps.py
  eMarket/app/forms.py
  eMarket/app/migrations/__init__.py
  eMarket/app/models.py
  eMarket/app/templates/app/login.html
  eMarket/app/templates/app/register.html
  eMarket/app/templates/app/registration_success.html
  eMarket/app/tests.py
  eMarket/app/urls.py
  eMarket/app/views.py
  eMarket/eMarket/__pycache__/__init__.cpython-312.pyc
  eMarket/eMarket/__pycache__/settings.cpython-312.pyc
  eMarket/eMarket/__pycache__/urls.cpython-312.pyc
  eMarket/eMarket/settings.py
  eMarket/eMarket/urls.py
Labels: enhancement

#48 Various Bug Fixes See Description
  eMarket/app/__pycache__/__init__.cpython-312.pyc
  eMarket/app/__pycache__/admin.cpython-312.pyc
  eMarket/app/__pycache__/apps.cpython-312.pyc
  eMarket/app/__pycache__/forms.cpython-312.pyc
  eMarket/app/__pycache__/models.cpython-312.pyc
  eMarket/app/__pycache__/urls.cpython-312.pyc
  eMarket/app/__pycache__/views.cpython-312.pyc
  eMarket/app/forms.py
  eMarket/app/migrations/0001_initial.py
  eMarket/app/migrations/__pycache__/0001_initial.cpython-312.pyc
  eMarket/app/migrations/__pycache__/__init__.cpython-312.pyc
  eMarket/app/templates/app/logout.html
  eMarket/app/templates/app/product_list.html
  eMarket/app/urls.py
  eMarket/app/views.py
  eMarket/db.sqlite3
  eMarket/eMarket/__pycache__/__init__.cpython-312.pyc
  eMarket/eMarket/__pycache__/settings.cpython-312.pyc
  eMarket/eMarket/__pycache__/urls.cpython-312.pyc
  eMarket/eMarket/settings.py
  eMarket/eMarket/urls.py
Labels: bug

#49 Added utils.py
  utils.py
Labels: Back-End

#50 Fixing placement of utils.py
  eMarket/app/utils.py
Labels: bug, Back-End

#54 Registration form + dashboard HTML files
  eMarket/app/__pycache__/__init__.cpython-312.pyc
  eMarket/app/__pycache__/admin.cpython-312.pyc
  eMarket/app/__pycache__/apps.cpython-312.pyc
  eMarket/app/__pycache__/forms.cpython-312.pyc
  eMarket/app/__pycache__/models.cpython-312.pyc
  eMarket/app/__pycache__/urls.cpython-312.pyc
  eMarket/app/__pycache__/views.cpython-312.pyc
  eMarket/app/admin.py
  eMarket/app/forms.py
  eMarket/app/migrations/0002_loginform_user_user_type.py
  eMarket/app/migrations/0003_remove_user_user_type_user_usertype.py
  eMarket/app/migrations/0004_rename_usertype_user_user_type.py
  eMarket/app/migrations/__pycache__/0001_initial.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0002_loginform_user_user_type.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0003_remove_user_user_type_user_usertype.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0004_rename_usertype_user_user_type.cpython-312.pyc
  eMarket/app/migrations/__pycache__/__init__.cpython-312.pyc
  eMarket/app/models.py
  eMarket/app/templates/app/admin_dashboard.html
  eMarket/app/templates/app/seller_dashboard.html
  eMarket/app/urls.py
  eMarket/app/views.py
  eMarket/db.sqlite3
  eMarket/eMarket/__pycache__/__init__.cpython-312.pyc
  eMarket/eMarket/__pycache__/settings.cpython-312.pyc
  eMarket/eMarket/__pycache__/urls.cpython-312.pyc
  eMarket/eMarket/__pycache__/wsgi.cpython-312.pyc
Labels: Back-End

#60 Models bug fixed + tests.py
  eMarket/app/__pycache__/__init__.cpython-312.pyc
  eMarket/app/__pycache__/admin.cpython-312.pyc
  eMarket/app/__pycache__/apps.cpython-312.pyc
  eMarket/app/__pycache__/forms.cpython-312.pyc
  eMarket/app/__pycache__/models.cpython-312.pyc
  eMarket/app/__pycache__/urls.cpython-312.pyc
  eMarket/app/__pycache__/views.cpython-312.pyc
  eMarket/app/migrations/0001_initial.py
  eMarket/app/migrations/0002_loginform_user_user_type.py
  eMarket/app/migrations/0003_remove_user_user_type_user_usertype.py
  eMarket/app/migrations/0004_rename_usertype_user_user_type.py
  eMarket/app/migrations/__pycache__/0001_initial.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0002_loginform_user_user_type.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0003_remove_user_user_type_user_usertype.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0004_rename_usertype_user_user_type.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0005_remove_buyer_user_ptr_alter_cart_user_and_more.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0006_alter_cart_user.cpython-312.pyc
  eMarket/app/migrations/__pycache__/__init__.cpython-312.pyc
  eMarket/app/models.py
  eMarket/app/tests.py
  eMarket/db.sqlite3
  eMarket/eMarket/__pycache__/__init__.cpython-312.pyc
  eMarket/eMarket/__pycache__/settings.cpython-312.pyc
  eMarket/eMarket/__pycache__/urls.cpython-312.pyc
  eMarket/eMarket/__pycache__/wsgi.cpython-312.pyc
Labels: Back-End

#59 Link Registration page to login page
  eMarket/app/templates/app/login.html
Labels: Front-End

#65 Merge Production to ji256-patch-1
  CONTRIBUTING.md
  README.md
  eMarket/app/templates/app/login.html
Labels: DateBase

#66 Merging Production changes into Codespace template branch
  CONTRIBUTING.md
  README.md
  db.sqllite3.db
  eMarket/app/templates/app/login.html
Labels: enhancement

#68 Fixed Database file
  db.sqllite3.sql
Labels: DateBase

#71 Update db.sqllite3.sql
  db.sqllite3.sql
Labels: Front-End

#70 Added 'Add product' feature
  eMarket/app/__pycache__/__init__.cpython-312.pyc
  eMarket/app/__pycache__/admin.cpython-312.pyc
  eMarket/app/__pycache__/apps.cpython-312.pyc
  eMarket/app/__pycache__/forms.cpython-312.pyc
  eMarket/app/__pycache__/models.cpython-312.pyc
  eMarket/app/__pycache__/tests.cpython-312.pyc
  eMarket/app/__pycache__/urls.cpython-312.pyc
  eMarket/app/__pycache__/views.cpython-312.pyc
  eMarket/app/forms.py
  eMarket/app/migrations/__pycache__/0001_initial.cpython-312.pyc
  eMarket/app/migrations/__pycache__/__init__.cpython-312.pyc
  eMarket/app/templates/app/add_product.html
  eMarket/app/templates/app/seller_dashboard.html
  eMarket/app/urls.py
  eMarket/app/views.py
  eMarket/db.sqlite3
  eMarket/eMarket/__pycache__/__init__.cpython-312.pyc
  eMarket/eMarket/__pycache__/settings.cpython-312.pyc
  eMarket/eMarket/__pycache__/urls.cpython-312.pyc
  eMarket/eMarket/__pycache__/wsgi.cpython-312.pyc
Labels: Back-End
