Repository Newt-Tea/eMarket-MSU-Intro-to-SE_Group1, pull requests merged in 2024-11, with the labels that each got.

#83 Various improvements (see desc.)
  eMarket/app/__pycache__/__init__.cpython-312.pyc
  eMarket/app/__pycache__/admin.cpython-312.pyc
  eMarket/app/__pycache__/apps.cpython-312.pyc
  eMarket/app/__pycache__/forms.cpython-312.pyc
  eMarket/app/__pycache__/models.cpython-312.pyc
  eMarket/app/__pycache__/tests.cpython-312.pyc
  eMarket/app/__pycache__/urls.cpython-312.pyc
  eMarket/app/__pycache__/views.cpython-312.pyc
  eMarket/app/admin.py
  eMarket/app/migrations/0001_initial.py
  eMarket/app/migrations/__pycache__/0001_initial.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0002_loginform_user_user_type.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0002_product_stock.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0003_alter_cart_quantity_alter_product_price.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0003_remove_user_user_type_user_usertype.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0004_rename_usertype_user_user_type.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0004_user_pending.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0005_remove_buyer_user_ptr_alter_cart_user_and_more.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0005_user_creation_time.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0006_alter_cart_user.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0006_alter_user_creation_time.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0007_alter_user_creation_time.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0008_remove_user_creation_time.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0009_product_date_created.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0010_product_sellerusername.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0011_rename_sellerusername_product_seller_username.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0012_remove_product_seller_username_product_sellerid.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0013_alter_product_sellerid.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0014_alter_product_sellerid.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0015_rename_sellerid_product_seller_username.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0016_alter_product_seller_username.cpython-312.pyc
  eMarket/app/migrations/__pycache__/__init__.cpython-312.pyc
  eMarket/app/models.py
  eMarket/app/templates/app/logout.html
  eMarket/app/templates/app/product_list.html
  eMarket/app/tests.py
  eMarket/app/urls.py
  eMarket/app/views.py
  eMarket/db.sqlite3
  eMarket/eMarket/__pycache__/__init__.cpython-312.pyc
  eMarket/eMarket/__pycache__/settings.cpython-312.pyc
  eMarket/eMarket/__pycache__/urls.cpython-312.pyc
  eMarket/eMarket/__pycache__/wsgi.cpython-312.pyc
  eMarket/eMarket/settings.py
  eMarket/eMarket_db.sqbpro
Labels: Back-End, DateBase

#87 Add Actions workflow to merge production into all branches
  .github/workflows/update-prod.yml
Labels: enhancement

#89 HTML Updates
  eMarket/app/forms.py
  eMarket/app/templates/app/checkout.html
  eMarket/app/templates/app/order_detail.html
  eMarket/app/templates/app/order_history.html
  eMarket/app/templates/app/registration_success.html
  eMarket/app/urls.py
  eMarket/app/views.py
  eMarket/db.sqlite3
Labels: Front-End

#98 Changed models and admin, fixed database
  eMarket/app/admin.py
  eMarket/app/migrations/0001_initial.py
  eMarket/app/migrations/0002_alter_order_cart_alter_order_user.py
  eMarket/app/migrations/0003_alter_order_user.py
  eMarket/app/migrations/__init__.py
  eMarket/app/migrations/__pycache__/0001_initial.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0002_alter_order_cart_alter_order_user.cpython-312.pyc
  eMarket/app/migrations/__pycache__/__init__.cpython-312.pyc
  eMarket/app/models.py
  eMarket/db.sqlite3
Labels: Back-End, DateBase

#106 Order changes + test updates
  eMarket/app/forms.py
  eMarket/app/migrations/0001_initial.py
  eMarket/app/migrations/0002_alter_order_cart_alter_order_user.py
  eMarket/app/migrations/0003_alter_order_user.py
  eMarket/app/models.py
  eMarket/app/tests.py
  eMarket/app/utils.py
  eMarket/db.sqlite3
Labels: Back-End, DateBase

#99 Home page
  .gitattributes
  eMarket/app/templates/app/home.html
  eMarket/app/templates/app/logout.html
  eMarket/app/templates/app/order_history.html
  eMarket/app/urls.py
  eMarket/app/views.py
  eMarket/db.sqlite3
  eMarket/eMarket/settings.py
  eMarket/static/app/home.css
  eMarket/staticfiles/app/add_product.css
  eMarket/staticfiles/app/home.css
  eMarket/staticfiles/app/login.css
  eMarket/staticfiles/app/logout.css
  eMarket/staticfiles/app/order_history.css
  eMarket/staticfiles/app/product_details.css
  eMarket/staticfiles/app/product_list.css
  eMarket/staticfiles/app/shopping_cart.css
Labels: Front-End

#101 Seller dashboard
  .gitattributes
  eMarket/app/forms.py
  eMarket/app/migrations/0001_initial.py
  eMarket/app/migrations/__pycache__/0001_initial.cpython-312.pyc
  eMarket/app/models.py
  eMarket/app/templates/app/create_product.html
  eMarket/app/templates/app/logout.html
  eMarket/app/templates/app/product_list.html
  eMarket/app/templates/app/seller_dashboard.html
  eMarket/app/urls.py
  eMarket/app/views.py
  eMarket/db.sqlite3
  eMarket/static/app/product_list.css
  eMarket/staticfiles/app/product_list.css
Labels: Front-End, Back-End, DateBase

#104 Search sort on Product List
  eMarket/app/forms.py
  eMarket/app/migrations/0001_initial.py
  eMarket/app/migrations/__pycache__/0001_initial.cpython-312.pyc
  eMarket/app/migrations/__pycache__/0002_alter_order_cart_alter_order_user.cpython-312.pyc
  eMarket/app/migrations/__pycache__/__init__.cpython-312.pyc
  eMarket/app/templates/app/product_list.html
  eMarket/app/utils.py
  eMarket/app/views.py
  eMarket/db.sqlite3
Labels: Front-End, Back-End

#109 Use Decimal for price and total fields in Product and Order models to prevent typing error; Add new order with multiple products
  eMarket/app/models.py
  eMarket/db.sqlite3
Labels: bug

#112 Enhance button styles in product details
  eMarket/staticfiles/app/product_details.css
Labels: Front-End

#113 Docstrings
  Testing proof/User Login Logout.png
  eMarket/app/forms.py
  eMarket/app/models.py
  eMarket/app/views.py
Labels: documentation

#115 Add Login URL to settings
  eMarket/eMarket/settings.py
Labels: Back-End

#125 Add link to view pending products in admin dashboard
  eMarket/app/templates/app/admin_dashboard.html
Labels: Front-End

#122 Update project type on README.md
  README.md
Labels: documentation

#130 Admin dashboard CSS
  eMarket/static/app/admin_dashboard.css
Labels: Front-End

#127 Added admin functions to tests.py
  eMarket/app/tests.py
Labels: Back-End

#134 Add styling and structure to admin and user product lists
  eMarket/app/templates/app/admin_product_list.html
  eMarket/app/templates/app/user_list.html
  eMarket/static/app/admin_product_list.css
  eMarket/static/app/user_list.css
  eMarket/staticfiles/app/admin_dashboard.css
  eMarket/staticfiles/app/admin_product_list.css
  eMarket/staticfiles/app/seller_dashboard.css
  eMarket/staticfiles/app/user_list.css
Labels: Front-End
